name: Build and Tag Docker Image

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
      - stable
  workflow_dispatch:

jobs:
  build-scan-push:
    uses: r0ps3c/gh-shared-workflows/.github/workflows/docker-build-scan-push.yml@888bf82066a53e73b6ce21f5be304b74e4aeb104 # main
    with:
      image-ref: unifi-network:main
      version-extract-command: "dpkg -s unifi | grep '^Version:' | awk '{print $2}'"
      test-command: make test-structure && make test-standalone && make test-integration
    secrets: inherit
